---
version: "2.1"
services:
  minetest_zfn_00:
    image: ghcr.io/linuxserver/minetest:latest
    # image: lspipepr/minetest:amd64-5.6.1-pkg-865a468e-pr-48
    container_name: minetest_zfn_00
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname augsburg --world worlds --port 30100 --logfile /config/.minetest/logs/augsburg2050.log
    volumes:
      - ./:/config/.minetest
    ports:
      - 30100:30100/udp
    restart: unless-stopped

